# Generated by Django 5.1.3 on 2024-12-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mines', '0005_carbonsink_emissionrecord_gapanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emissionrecord',
            name='excavation_hours',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
